In [267]:
import pandas as pd 
import numpy as np 

from sklearn.metrics import  accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.impute import MissingIndicator
from sklearn . impute import SimpleImputer

In [268]:
df = pd.read_csv('train.csv' , usecols=['Age' , 'Fare' , 'Survived'])

In [269]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [270]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2 , random_state=2)

In [271]:
x_train

      Age      Fare
30   40.0   27.7208
10    4.0   16.7000
873  47.0    9.0000
182   9.0   31.3875
876  20.0    9.8458
..    ...       ...
534  30.0    8.6625
584   NaN    8.7125
493  71.0   49.5042
527   NaN  221.7792
168   NaN   25.9250

[712 rows x 2 columns]

In [272]:
si = SimpleImputer(strategy='mean')
x_train_impute = si.fit_transform(x_train) 
x_test_impute = si.transform(x_test)

In [273]:
lr = LogisticRegression()

lr.fit(x_train_impute , y_train)

y_pred = lr.predict(x_test_impute)
accuracy_score(y_test , y_pred)

0.6145251396648045

# ---------------------------------------------------------------------- 
# **- With missing Indicator**
# ---------------------------------------------------------------------

In [274]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2 , random_state=2)

In [275]:
Mi  =  MissingIndicator()

Mi.fit(x_train)
x_train_mi =Mi.transform(x_train)

In [276]:
x_test_mi =Mi.transform(x_test)

In [277]:
x_train_mi.shape

(712, 1)

In [278]:
x_train.shape

(712, 2)

In [279]:
x_train ['Age_na'] = x_train_mi 
x_test['Age_na'] = x_test_mi

In [280]:
x_test

      Age     Fare  Age_na
707  42.0  26.2875   False
37   21.0   8.0500   False
615  24.0  65.0000   False
169  28.0  56.4958   False
68   17.0   7.9250   False
..    ...      ...     ...
89   24.0   8.0500   False
80   22.0   9.0000   False
846   NaN  69.5500    True
870  26.0   7.8958   False
251  29.0  10.4625   False

[179 rows x 3 columns]

In [281]:
Si = SimpleImputer()

In [282]:
x_train_imp = Si.fit_transform(x_train)
x_test_imp = Si.transform(x_test)

In [283]:
lr.fit(x_train_imp , y_train)

y_pred = lr.predict(x_test_imp)

accuracy_score(y_test , y_pred)

0.6312849162011173

# Missing indicator with SimpleImputer

In [284]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2 , random_state=2)

In [285]:
si = SimpleImputer(add_indicator=True)

In [286]:
x_train = si.fit_transform(x_train)
x_test = si.transform(x_test)

In [287]:
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test_imp)

accuracy_score(y_test , y_pred)

0.6312849162011173