In [1095]:
import pandas as pd
import numpy as n

In [1096]:
df = pd.read_csv("customer.csv")

In [1097]:
df.sample(5)

    age  gender   review education purchased
12   51    Male     Poor    School        No
49   25  Female     Good        UG        No
11   74    Male     Good        UG       Yes
29   83  Female  Average        UG       Yes
9    74    Male     Good        UG       Yes

In [1098]:
df = df.iloc[: ,2:]

In [1099]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# Ordinal Encoding

In [1100]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],
                                                 df.iloc[:,-1],
                                                 test_size=0.2)

x_train.shape , x_test.shape

((40, 2), (10, 2))

In [1101]:
x_train

     review education
13  Average    School
47     Good        PG
22     Poor        PG
7      Poor    School
40     Good    School
4   Average        UG
3      Good        PG
10     Good        UG
21  Average        PG
36     Good        UG
48     Good        UG
8   Average        UG
18     Good    School
0   Average    School
17     Poor        UG
41     Good        PG
27     Poor        PG
2      Good        PG
33     Good        PG
12     Poor    School
35     Poor    School
28     Poor    School
9      Good        UG
45     Poor        PG
44  Average        UG
38     Good    School
42     Good        PG
23     Good    School
15     Poor        UG
31     Poor    School
20  Average    School
25     Good    School
37  Average        PG
26     Poor        PG
46     Poor        PG
34  Average    School
32  Average        UG
19     Poor        PG
14     Poor        PG
49     Good        UG

In [1102]:
from sklearn.preprocessing import OrdinalEncoder

In [1103]:
OE = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [1104]:
OE.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [1105]:
x_train_Encoded = OE.transform(x_train)
x_test_Encoded = OE.transform(x_test)

In [1106]:
x_train_Encoded = pd.DataFrame(x_train_Encoded , columns=x_train.columns) # Converting Series into DF BEcause sKlearn function return a serires always

In [1107]:
OE.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

## Label Encoding

- it is always used for target categorical column

In [1108]:
from sklearn.preprocessing import LabelEncoder

In [1109]:
le = LabelEncoder()

In [1110]:
le.fit(y_train)

LabelEncoder()

In [1111]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [1112]:
y_train_Encoded = le.transform(y_train)
y_test_Encoded = le.transform(y_test)

In [1113]:
y_train_Encoded

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0])