In [206]:
import pandas as pd
import numpy as np

In [207]:
df = pd.read_csv("cars.csv")

In [208]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [209]:
df['brand'].value_counts(ascending=False)# Checking which brand has more value

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [210]:
df['brand'].nunique() #Checking unique  brands has

32

In [211]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [212]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# One Hot Encoding Using pandas

In [213]:
pd.get_dummies(df , columns=['fuel' ,'owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

# K-1 OHE Encoding (Removing first column) solving multicollinearity prob

-- Pandas cannot remember the order of columns which mattters in ml So we alway use Sklearn to do Encoding if Our goal is to make ML Model

In [214]:
pd.get_dummies(df , columns=['fuel' ,'owner'],dtype=int,drop_first=True) # drop first removing first column

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

# OHE With Sklearn

In [215]:
from sklearn.model_selection import train_test_split

In [216]:
x_train , x_test , y_train , y_test = train_test_split( 
    df.iloc[:,0:4],
    df.iloc[: ,-1],
    test_size=0.2,
    random_state=0
)

x_train.shape , x_test.shape

((6502, 4), (1626, 4))

In [217]:
from sklearn.preprocessing import OneHotEncoder

In [218]:
OHE = OneHotEncoder(drop='first'  ,dtype = np.int32 ,sparse_output=False) # Sparse_output = false to stop making  sparse aarray if it was not given we need to use toarray to see sparse array

In [219]:
x_train_new = OHE.fit_transform(x_train[['fuel' , 'owner']]) #.toarray()  if sparse_output not use in OneHotEncoder()

In [220]:
x_test_new = OHE.transform(x_test[['fuel' , 'owner']])  #.toarray()  if sparse_Output not use in OneHotEncoder()

In [221]:
np.hstack((x_train[['brand' , 'km_driven']].values , x_train_new)).shape

(6502, 9)

# OneHotEncoding with Top Cat

In [224]:
count = df['brand'].value_counts()

In [225]:
df['brand'].nunique()
threshold = 100

In [229]:
repl = count[count <= threshold].index

In [235]:
pd.get_dummies(df['brand'].replace(repl ,'Uncomon') , dtype=np.int32).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Uncomon,Volkswagen
2078,0,0,0,0,0,0,0,0,0,0,0,1,0
3494,0,0,0,0,1,0,0,0,0,0,0,0,0
752,0,0,0,0,0,0,0,0,0,0,1,0,0
3356,0,0,0,0,0,0,0,0,0,0,0,0,1
4656,0,0,0,0,0,0,1,0,0,0,0,0,0