In [43]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score , mean_absolute_error ,mean_squared_error

from sklearn.linear_model import LinearRegression

In [44]:
df = pd.read_csv("Multiple_Linear_Reg.csv")

In [45]:
df.head()

   Study_Hours  Attendance  Previous_Score  Sleep_Hours  Final_Score
0         4.37       51.57           75.31         4.26        96.57
1         9.56       81.82           44.63         6.66       114.59
2         7.59       65.72           48.89         6.70       104.49
3         6.39       75.43           89.42         7.19       122.79
4         2.40       95.38           73.35         7.63       105.76

In [46]:
df.shape

(100, 5)

In [47]:
x = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [48]:
y

0      96.57
1     114.59
2     104.49
3     122.79
4     105.76
       ...
95    109.73
96    124.86
97     97.46
98     95.30
99     88.96
Name: Final_Score, Length: 100, dtype: float64

In [49]:
x_train ,x_test , y_train ,y_test = train_test_split(x,y,test_size=0.2 , random_state=2)

In [50]:
lr = LinearRegression()

In [51]:
lr.fit(x_train,y_train)

LinearRegression()

In [52]:
y_pred = lr.predict(x_test)

In [53]:
print("MAE", mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("r2",r2_score(y_test,y_pred))

MAE 2.0323785271232295
MSE 6.570963528321636
r2 0.9590831696802249

In [54]:
x_test.shape

(20, 4)

In [55]:
r2 = r2_score(y_test,y_pred)
1 - ((1-r2)*(20-1) / (20-1-4))

0.9481720149282848

In [56]:
new_df = df.copy()
new_df['Temp'] =  np.random.random(100)
new_df = new_df[['Study_Hours','Attendance','Previous_Score','Temp','Sleep_Hours' , 'Final_Score']]

new_df.sample(5)

,Study_Hours,Attendance,Previous_Score,Temp,Sleep_Hours,Final_Score
13,2.91,90.41,52.33,0.801071,8.81,98.51
21,2.26,94.80,71.26,0.155315,7.57,102.24
12,8.49,96.48,75.86,0.833811,4.13,130.43
68,1.67,52.04,59.77,0.056009,4.98,67.19
99,1.97,88.99,44.69,0.473456,7.77,88.96

In [57]:
x1 = new_df.iloc[:,0:5]
y1 = new_df.iloc[:,-1]

In [58]:
x_train1 ,x_test1 , y_train1 ,y_test1 = train_test_split(x1,y1,test_size=0.2 , random_state=2)

In [63]:
lr = LinearRegression()
lr.fit(x_train1,y_train1)
y_pred = lr.predict(x_test1)

In [60]:
print("MAE", mean_absolute_error(y_test1,y_pred))
print("MSE",mean_squared_error(y_test1,y_pred))
print("r2",r2_score(y_test1,y_pred))

MAE 2.019572535133796
MSE 6.637682861785637
r2 0.9586677140724393

In [61]:
r21 = r2_score(y_test1,y_pred)
1 - ((1-r21)*(20-1) / (20-1-4))

0.9476457711584232

In [64]:
lr.coef_

array([4.54022747, 0.35736125, 0.55444283, 0.60927063, 2.22596829])

In [65]:
lr.intercept_

np.float64(2.150082726203536)